version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR started on 'date'
      - aws --version
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 183983006583.dkr.ecr.ap-southeast-1.amazonaws.com
      - echo setting repository URI...
      - REPOSITORY_URI=183983006583.dkr.ecr.ap-southeast-1.amazonaws.com/romeshdhananjaya-com-ecr
      - echo setting image tag...
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo building and tagging the image on 'date'
      - echo running mvn clean install...
      - mvn clean install
      - echo building the docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo tagging the docker image...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing the docker image to ECR started on 'date'
      - echo pushing to repository...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo setting container name...
      - DOCKER_CONTAINER_NAME=romeshdhananjaya-com-be
      - echo writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinition.json...
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json