version: '3.8'

services:
  backend:
    container_name: 'romas-scribbles-backend'
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - 'MONGO_URI=mongodb://romas-scribbles-mongodb:27017/romas-scribbles'
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo:latest'
    container_name: 'romas-scribbles-mongodb'
    environment:
      - 'MONGO_INITDB_DATABASE=romas-scribbles'
#      - 'MONGO_INITDB_ROOT_PASSWORD=root-roma-secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root-roma'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'
volumes:
    mongodb_data: